In [1]:
import numpy as np

In [2]:
marks = [
    [99, 93, 100],
    [96, 99, 78],
    [100, 97, 89]
]

In [6]:
n1 = np.array(marks, dtype=np.int16)
print(n1)
print(n1.ndim)
print(n1.shape)
print(type(n1))

[[ 99  93 100]
 [ 96  99  78]
 [100  97  89]]
2
(3, 3)
<class 'numpy.ndarray'>


In [12]:
# indexing
print(n1[1])
print(n1[-1])
print(n1[0][-1]) # python indexing on 2D
print(n1[0, -1]) # optimal numpy way

# multiple indexing
print(n1[[0, -1]])

[96 99 78]
[100  97  89]
100
100
[[ 99  93 100]
 [100  97  89]]


In [15]:
# indexing + modify
print(n1)
n1[0, 1] = 94
print(n1)
n2 = n1.copy()
print(n2)

[[ 99  94 100]
 [ 96  99  78]
 [100  97  89]]
[[ 99  94 100]
 [ 96  99  78]
 [100  97  89]]
[[ 99  94 100]
 [ 96  99  78]
 [100  97  89]]


In [17]:
n2[-1] = 0
print(n2)

[[ 99  94 100]
 [ 96  99  78]
 [  0   0   0]]


In [22]:
# slicing
print(n1)
print(n1[:2])
print(n1[-2:, :2]) # row + col slicing
print(n1[:2, -2:])

[[ 99  94 100]
 [ 96  99  78]
 [100  97  89]]
[[ 99  94 100]
 [ 96  99  78]]
[[ 96  99]
 [100  97]]
[[ 94 100]
 [ 99  78]]


In [25]:
# slicing + indexing
print(n1)
print(n1[:2, [0, -1]])

[[ 99  94 100]
 [ 96  99  78]
 [100  97  89]]
[[ 99 100]
 [ 96  78]]


In [28]:
n3 = n1[[0, -1]]
print(n3[:, [0, -1]])

[[ 99 100]
 [100  89]]


In [33]:
# statistical
print(n1)
print(n1.mean(axis=0))
print(n1.sum(axis=1))

[[ 99  94 100]
 [ 96  99  78]
 [100  97  89]]
[98.33333333 96.66666667 89.        ]
[293 273 286]


In [34]:
m1 = np.array([
    [2, 3],
    [5, 6]
])
m2 = np.array([
    [6, 4],
    [3, 8]
])
print(m1)
print(m2)

[[2 3]
 [5 6]]
[[6 4]
 [3 8]]


In [39]:
print(m1 + m2)
print(m1 - m2)
print(m1 * m2) # not matrix multiplication
print(np.dot(m1, m2))

[[ 8  7]
 [ 8 14]]
[[-4 -1]
 [ 2 -2]]
[[12 12]
 [15 48]]
[[21 32]
 [48 68]]
