In [13]:
import numpy as np
import numpy.random as rd

In [5]:
print(np.zeros(10))
print(np.ones(20))
print(np.arange(12, 23))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[12 13 14 15 16 17 18 19 20 21 22]


In [11]:
print(np.identity(3))
n1 = np.arange(1, 10).reshape(3, 3)
print(n1)
n2 = n1.ravel()
print(n2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


In [19]:
rd.rand(20)

array([0.03356503, 0.37989545, 0.63270068, 0.36897079, 0.41760157,
       0.2350897 , 0.70314317, 0.4960515 , 0.05633964, 0.56274629,
       0.74472053, 0.24506468, 0.93030502, 0.36151154, 0.05759281,
       0.49168038, 0.71074486, 0.51426104, 0.70397642, 0.57710105])

In [25]:
rd.randn(20)

array([-0.02024103,  0.49460104, -0.25037724,  1.53927706,  1.17199517,
        0.74005462,  1.81976318, -0.20339473,  0.25817202, -0.17051501,
        0.42031128,  1.54312378,  0.08441586, -0.18119888, -0.63862908,
        0.3244291 , -0.83866302, -0.52552614, -2.11332239, -0.12988444])