In [4]:
import numpy as np

In [5]:
marks = [10, 4, 5, 6, 5, 4, 10, 3, 2, 1, 10, 9, 8]

In [11]:
# numpy data structure first to perform numpy operations
# ndarray
n1 = np.array(marks, dtype=np.int8)
print(type(n1))
print(n1)
print(n1.ndim)
print(n1.shape)
print(n1.dtype)

<class 'numpy.ndarray'>
[10  4  5  6  5  4 10  3  2  1 10  9  8]
1
(13,)
int8


In [25]:
# indexing
print(n1[0])
print(n1[2])
print(n1[-1])
print(n1[-3])

# multiple indexing
print(n1[[0, -1, -3, 1]])

0
5
8
10
[ 0  8 10  6]


In [19]:
# indexing + modify
n1[1] = 6
print(n1)

# indexing + modify (vectorized) -- broadcasting
n1[[0, -2]] = 0
print(n1)

[10  6  5  6  5  4 10  3  2  1 10  9  8]
[ 0  6  5  6  5  4 10  3  2  1 10  0  8]


In [24]:
# slicing
print(n1)
print(n1[0:3])
print(n1[:3])
print(n1[3:])
print(n1[-4:])

[ 0  6  5  6  5  4 10  3  2  1 10  0  8]
[0 6 5]
[0 6 5]
[ 6  5  4 10  3  2  1 10  0  8]
[ 1 10  0  8]


In [28]:
# slicing + modify
print(n1)
n1[:4] = 0 # broadcasting
print(n1)

[ 0  0  0  0  5  4 10  3  2  1 10  0  8]
[ 0  0  0  0  5  4 10  3  2  1 10  0  8]


In [31]:
# arithmetic operations
print(n1)
n2 = n1 + 1
print(n2)
n3 = n1 ** 2
print(n3)

[ 0  0  0  0  5  4 10  3  2  1 10  0  8]
[ 1  1  1  1  6  5 11  4  3  2 11  1  9]
[  0   0   0   0  25  16 100   9   4   1 100   0  64]


In [34]:
# relational operators
print(n1)
n4 = n1 == 0
print(n4)
n5 = n1 > 5
print(n5)

[ 0  0  0  0  5  4 10  3  2  1 10  0  8]
[ True  True  True  True False False False False False False False  True
 False]
[False False False False False False  True False False False  True False
  True]


In [41]:
# filtering
print(n1)
n6 = n1[n1 > 5]
print(n6)

n7 = n1[(n1 == 10) | (n1 < 5)]
print(n7)

[ 0  0  0  0  5  4 10  3  2  1 10  0  8]
[10 10  8]
[ 0  0  0  0  4 10  3  2  1 10  0]


In [49]:
# statistical
print(n1)
print(n1.min())
print(n1.max())
print(n1.mean())
print(np.median(n1))
print(n1.std())
print(n1.var())

[ 0  0  0  0  5  4 10  3  2  1 10  0  8]
0
10
3.3076923076923075
2.0
3.6874968659098104
13.597633136094675


In [50]:
n8 = np.array([10, 20, 5, 14], dtype=np.int8)
n8

array([10, 20,  5, 14], dtype=int8)

In [52]:
print(n8.cumsum())
print(n8.cumprod())

[10 30 35 49]
[   10   200  1000 14000]


In [58]:
print(n1)
n9 = np.where(n1 > 5, 1, 0)
print(n9)
n10 = np.where(n1 > 5)
print(n10)

[ 0  0  0  0  5  4 10  3  2  1 10  0  8]
[0 0 0 0 0 0 1 0 0 0 1 0 1]
(array([ 6, 10, 12]),)
